apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-issure 
  namespace: any
spec:
  secretName: example-issuer-account-key
  duration: 2160h # 90d
  renewBefore: 360h # 15d

  subject:
    organizations:
      - examples.com
  dnsNames:
    - example.com
    - example.com
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
    group: cert-manager.io
